### PR TITLE
Fix prompt for multi-byte characters.

### LINKED ISSUE #40: Multi-Byte-Strings
Thanks for maintaining this nice widget!
I noticed a bug with handling characters that consists of multiple bytes.

For instance, the following leads to a panic:

```rust
let mut test = TextState::new();
test.push('Ö');
test.push('a');
```

### PR DESCRIPTION
**Pull request by frederictobiasc**
Before this contribution, entering characters that consists of multiple bytes lead to undesired behaviour such as panics.
This results from the position previous position handling inside the prompt.
The String::len() returns the size of the string in bytes. Since a single unicode scalar value may consist of multiple bytes, this is not useful to determine the position inside the prompt. The panic occured in the State::push() method and resulted from the attempt to insert at a byte index that does not represent a character boundary.
See:
https://doc.rust-lang.org/stable/std/primitive.str.html#method.len https://doc.rust-lang.org/stable/std/string/struct.String.html#method.insert

Fixes https://github.com/joshka/tui-prompts/issues/40

### CODE REVIEW

**Review by joshka — CHANGES_REQUESTED** [review]
Thanks for fixing this. There's a couple of small things to fix if you don't mind.

**Comment by frederictobiasc** [comment]
Hi, thanks for your quick response! I addressed your comments and rebased.

**Comment by joshka** [comment]
> There are, however, two tests that fail:

I've been meaning to look at them but haven't done so yet: https://github.com/joshka/tui-prompts/issues/29

**Review by joshka — APPROVED** [review]
LGTM. Thanks for fixing this up!

**Pull request merged**
